import {
  OnChainSourceEntry,
  OnChainDetailedMetric,
  CorrelationPairData
} from '../../types';

export const PRIMARY_ONCHAIN_SOURCES: OnChainSourceEntry[] = [
  {
    id: 'look-into-bitcoin',
    name: 'Look Into Bitcoin',
    category: 'On-Chain Valuation & Cycles',
    url: 'https://www.lookintobitcoin.com',
    description: 'Plataforma referente en modelos de valoración cíclica y análisis on-chain fundada por Philip Swift. Especializada en métricas de largo plazo para inversores institucionales.',
    keyIndicators: ['MVRV Z-Score', 'Puell Multiple', 'Stock-to-Flow Model', '200W MA Heatmap', 'RHODL Ratio', 'Reserve Risk'],
    freeTier: true,
    frequency: 'Diaria (cierre de vela UTC)',
    apiSupport: true,
    methodologyNote: 'Calcula ratios sobre el conjunto de UTXOs agregados en bloques confirmados.',
  },
  {
    id: 'cryptoquant',
    name: 'CryptoQuant',
    category: 'Exchanges & Flow Metrics',
    url: 'https://cryptoquant.com',
    description: 'Líder en monitoreo de flujos hacia y desde exchanges centralizados, balance de mineros, derivados de apalancamiento y flujos institucionales.',
    keyIndicators: ['Exchange Reserve', 'Netflows In/Out', 'Miner Outflow Index (MPI)', 'Estimated Leverage Ratio', 'aSOPR', 'SSR (Stablecoin Supply Ratio)'],
    freeTier: true,
    frequency: 'En tiempo real / Bloque a bloque',
    apiSupport: true,
    methodologyNote: 'Etiquetado algorítmico y heurístico de billeteras frías y calientes de exchanges globales.',
  },
  {
    id: 'coingecko',
    name: 'CoinGecko',
    category: 'Market Data & Explorers',
    url: 'https://www.coingecko.com/es/monedas/bitcoin',
    description: 'El agregador independiente de datos de mercado de criptomonedas más consultado del mundo. Métricas de liquidez global, volumen 24h, FDV y capitalización de mercado.',
    keyIndicators: ['Precio Spot Multidivisa', 'Volumen 24h Normalizado', 'Dominancia Global BTC %', 'Máximo Histórico (ATH)', 'Liquidez en Pares DEX/CEX'],
    freeTier: true,
    frequency: 'Tiempo Real (sub-minuto)',
    apiSupport: true,
    methodologyNote: 'Filtra volumen falso y wash-trading mediante algoritmos Trust Score.',
  },
  {
    id: 'coinmarketcap',
    name: 'CoinMarketCap',
    category: 'Market Data & Explorers',
    url: 'https://coinmarketcap.com/es/currencies/bitcoin/',
    description: 'Plataforma líder en seguimiento de precios, reservas CEX (Proof of Reserves), profundidad de libros de órdenes y ponderación de índices de mercado.',
    keyIndicators: ['CEX Proof of Reserves', 'Circulating vs Max Supply', 'Market Breadth', 'Fear & Greed Index', 'DEX Aggregated Trades'],
    freeTier: true,
    frequency: 'Tiempo Real',
    apiSupport: true,
    methodologyNote: 'Ponderación basada en volumen de transacciones reportadas y liquidez verificada.',
  },
  {
    id: 'cryptocompare',
    name: 'CryptoCompare',
    category: 'Market Data & Explorers',
    url: 'https://www.cryptocompare.com',
    description: 'Proveedor de datos institucionales de grado financiero, benchmarks CCCAGG y series históricas de ticks para backtesting cuantitativo.',
    keyIndicators: ['Índice CCCAGG', 'Order Book Depth 1% / 2%', 'Volatilidad Histórica 30d/90d', 'Tick Data de Alta Frecuencia'],
    freeTier: true,
    frequency: 'Streaming WebSocket / REST',
    apiSupport: true,
    methodologyNote: 'Metodología propietaria de precios de referencia para índices derivados y productos ETF.',
  },
  {
    id: 'bitbo',
    name: 'BitBo',
    category: 'On-Chain Valuation & Cycles',
    url: 'https://bitbo.io',
    description: 'Dashboard visual en tiempo real de métricas macroeconómicas de Bitcoin, tesorerías de empresas públicas, holdings de ETFs spot y cuenta regresiva de halving.',
    keyIndicators: ['Treasuries de Empresas (MicroStrategy, etc.)', 'Holdings de ETFs Spot (IBIT, FBTC)', 'Halving Countdown', 'Costo de Producción de Minería', 'Adopción Taproot'],
    freeTier: true,
    frequency: 'En vivo / Actualización continua',
    apiSupport: false,
    methodologyNote: 'Consolida reportes 13F ante la SEC con datos on-chain verificados de custodios.',
  },
  {
    id: 'blockchain-explorer',
    name: 'Blockchain.com Explorer & Mempool',
    category: 'Market Data & Explorers',
    url: 'https://www.blockchain.com/explorer / https://mempool.space',
    description: 'Exploradores nativos de la red Bitcoin para inspección forense de transacciones, tamaño de UTXO set, congestión de mempool y gráficos de hashrate histórico.',
    keyIndicators: ['Tamaño del Conjunto UTXO', 'Mempool Vsize y Backlog', 'Tarifas Recomendadas (sat/vB)', 'Tiempo Medio entre Bloques', 'Dificultad de Red'],
    freeTier: true,
    frequency: 'Instantánea por bloque',
    apiSupport: true,
    methodologyNote: 'Conexión directa a nodos completos Bitcoin Core (P2P bitcoind).',
  },
  {
    id: 'nodecharts',
    name: 'NodeCharts',
    category: 'On-Chain Valuation & Cycles',
    url: 'https://nodecharts.com',
    description: 'Plataforma analítica on-chain de alta precisión con enfoque hispanohablante. Especializada en cohortes de acumulación de ballenas, SOPR ajustado y HODL Waves.',
    keyIndicators: ['Cohortes de Ballenas (>1k BTC)', 'aSOPR (Adjusted SOPR)', 'Coin Days Destroyed (CDD)', 'Realized Price por Antigüedad', 'HODL Waves 1y+'],
    freeTier: true,
    frequency: 'Diaria y Horaria',
    apiSupport: true,
    methodologyNote: 'Algoritmos propios para aislar transferencias internas de exchanges de movimientos de billeteras soberanas.',
  },
  {
    id: 'bitcoin-visuals',
    name: 'Bitcoin Visuals',
    category: 'On-Chain Valuation & Cycles',
    url: 'https://bitcoinvisuals.com',
    description: 'Visualizador integral de estadísticas de la red Bitcoin y Lightning Network. Métricas de canales L2, capacidad en BTC, distribución geográfica de nodos y tamaño de bloque.',
    keyIndicators: ['Capacidad Total Lightning (BTC y USD)', 'Cantidad de Canales y Nodos Lightning', 'Tamaño Promedio de Bloque', 'Mediana de Tarifas de Transacción'],
    freeTier: true,
    frequency: 'Diaria',
    apiSupport: true,
    methodologyNote: 'Mapeo de la red gossip de Lightning Network mediante nodos observadores BOLT.',
  },
  {
    id: 'livecoinwatch',
    name: 'LiveCoinWatch',
    category: 'Market Data & Explorers',
    url: 'https://www.livecoinwatch.com',
    description: 'Plataforma de seguimiento en vivo con cálculo de diferenciales de arbitraje entre exchanges, precios en monedas fiduciarias globales y liquidez por par.',
    keyIndicators: ['Diferencial de Arbitraje Cross-Exchange', 'Métricas de Liquidez Instantánea', 'Profundidad de Mercado Spot', 'Conversión Multidivisa en Vivo'],
    freeTier: true,
    frequency: 'En tiempo real (1 segundo)',
    apiSupport: true,
    methodologyNote: 'Streaming directo de cotizaciones libro a libro desde más de 150 exchanges.',
  },
  {
    id: 'mataf',
    name: 'Mataf (Macro & Forex Correlations)',
    category: 'Macro, Correlations & AI',
    url: 'https://www.mataf.net',
    description: 'Herramienta de análisis cuantitativo macroeconómico y matriz de correlaciones de Pearson entre divisas fiduciarias, materias primas (Oro, Petróleo) y Bitcoin.',
    keyIndicators: ['Matriz de Correlación Pearson (30d, 90d, 1y)', 'Volatilidad Histórica Cruzada', 'Fuerza Relativa de Monedas', 'Beta contra el DXY'],
    freeTier: true,
    frequency: 'Horaria y Diaria',
    apiSupport: false,
    methodologyNote: 'Cálculo de coeficientes de covarianza normalizada sobre series de retornos logarítmicos.',
  },
  {
    id: 'stenox-ai',
    name: 'Stenox.ai',
    category: 'Macro, Correlations & AI',
    url: 'https://stenox.ai',
    description: 'Plataforma de inteligencia cuantitativa basada en IA para la detección de patrones anómalos en cadena, divergencias de volumen e indicadores predictivos de mercado.',
    keyIndicators: ['Detección de Anomalías On-Chain', 'Smart Money Momentum Index', 'Alertas de Divergencia Ballenas vs Retail', 'Sentiment AI Fusion Score'],
    freeTier: true,
    frequency: 'Tiempo Real',
    apiSupport: true,
    methodologyNote: 'Modelos de machine learning entrenados sobre grafos de transacciones y datos de libros de órdenes.',
  },
  {
    id: 'analisis-bitcoin',
    name: 'Análisis de Bitcoin (Framework Diego Beltramo)',
    category: 'On-Chain Valuation & Cycles',
    url: 'https://bitcoinintelligence.org/framework',
    description: 'Modelo integral de análisis fundamental de nueve capas desarrollado por Diego Eduardo Beltramo: Red, Minería, Liquidez, Covenants, Custodia, Regulación, Contabilidad, Macro y Psicosocial.',
    keyIndicators: ['Modelo de 9 Capas Fundamentales', 'Matriz de Factores BIS Score', 'Invariantes de Protocolo C++', 'Análisis de Incertidumbre Epistémica'],
    freeTier: true,
    frequency: 'Continuo',
    apiSupport: false,
    methodologyNote: 'Delimitación estricta de Hechos, Análisis, Opiniones e Incertidumbres sin determinismo.',
  },
  {
    id: 'correlaciones-macro',
    name: 'Motor de Correlaciones Cuantitativas',
    category: 'Macro, Correlations & AI',
    url: 'https://bitcoinintelligence.org/correlations',
    description: 'Motor analítico interno que correlaciona la acción de precio de Bitcoin frente a los activos macroeconómicos más influyentes: S&P 500, Oro, DXY, Nasdaq 100 y M2 Global.',
    keyIndicators: ['Correlación BTC vs Oro (Digital vs Físico)', 'Correlación BTC vs S&P 500 (Risk-on)', 'Correlación Inversa BTC vs DXY (Debasement Hedge)', 'Beta de Portafolio'],
    freeTier: true,
    frequency: 'Cálculo Diario',
    apiSupport: true,
    methodologyNote: 'Retornos logarítmicos con ventana móvil de 30, 90 y 365 días.',
  },
];

export const PRIMARY_ONCHAIN_METRICS: OnChainDetailedMetric[] = [
  {
    id: 'metric-mvrv-z',
    name: 'MVRV Z-Score',
    symbol: 'MVRV-Z',
    sourceId: 'look-into-bitcoin',
    sourceName: 'Look Into Bitcoin / Glassnode',
    sourceUrl: 'https://www.lookintobitcoin.com/charts/mvrv-zscore/',
    currentValue: 2.18,
    formattedValue: '2.18 σ',
    historicalRange: { min: -0.45, max: 11.2, mean: 1.85 },
    zones: {
      accumulation: { min: -1.0, max: 0.8, label: 'Zona de Infravaloración / Acumulación Fuerte' },
      neutral: { min: 0.8, max: 4.5, label: 'Zona de Valor Razonable / Tendencia Cíclica' },
      overheated: { min: 4.5, max: 12.0, label: 'Zona de Euforia / Techo de Mercado' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: '(Market Cap - Realized Cap) / Desviación Estándar(Market Cap)',
    interpretation: 'Mide la desviación del valor de mercado respecto al precio realizado de compra de todos los participantes. Valores superiores a 5.0 indican techos históricos; valores inferiores a 0.5 señalan suelos generacionales.',
    importance: 'CRITICAL',
  },
  {
    id: 'metric-puell-multiple',
    name: 'Puell Multiple',
    symbol: 'PUELL',
    sourceId: 'look-into-bitcoin',
    sourceName: 'Look Into Bitcoin',
    sourceUrl: 'https://www.lookintobitcoin.com/charts/puell-multiple/',
    currentValue: 1.28,
    formattedValue: '1.28x',
    historicalRange: { min: 0.28, max: 9.8, mean: 1.35 },
    zones: {
      accumulation: { min: 0.0, max: 0.5, label: 'Capitulación de Mineros (Compra Fuerte)' },
      neutral: { min: 0.5, max: 2.0, label: 'Equilibrio de Emisión Minera' },
      overheated: { min: 2.0, max: 10.0, label: 'Presión Vendedora de Mineros Alta' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: 'Valor Diario de Emisión de BTC (USD) / Media Móvil 365 días del Valor Diario de Emisión',
    interpretation: 'Evalúa la salud de los mineros. Ratios menores a 0.5 reflejan estrés extremo y capitulación de mineros; por encima de 2.5 alertan sobre euforia y toma de beneficios.',
    importance: 'CRITICAL',
  },
  {
    id: 'metric-sopr',
    name: 'SOPR (Spent Output Profit Ratio)',
    symbol: 'aSOPR',
    sourceId: 'cryptoquant',
    sourceName: 'CryptoQuant / NodeCharts',
    sourceUrl: 'https://cryptoquant.com/overview/btc-on-chain-data',
    currentValue: 1.018,
    formattedValue: '1.018',
    historicalRange: { min: 0.88, max: 1.15, mean: 1.002 },
    zones: {
      accumulation: { min: 0.8, max: 0.98, label: 'Ventas con Pérdidas Masivas (Reset)' },
      neutral: { min: 0.98, max: 1.03, label: 'Soporte Clave en Nivel 1.0' },
      overheated: { min: 1.03, max: 1.2, label: 'Toma Extrema de Beneficios en Cadena' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: 'Precio de Venta del UTXO gastado / Precio de Creación del UTXO',
    interpretation: 'Un SOPR > 1.0 indica que las monedas gastadas se venden con beneficio medio. En mercados alcistas saludables, la línea 1.0 actúa como un potente soporte de recarga.',
    importance: 'HIGH',
  },
  {
    id: 'metric-exchange-reserve',
    name: 'Reservas Totales en Exchanges',
    symbol: 'EX-RES',
    sourceId: 'cryptoquant',
    sourceName: 'CryptoQuant',
    sourceUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-details/exchange-reserve',
    currentValue: 2180450,
    formattedValue: '2,180,450 BTC',
    unit: 'BTC',
    historicalRange: { min: 2050000, max: 3200000, mean: 2550000 },
    zones: {
      accumulation: { min: 0, max: 2300000, label: 'Choque de Oferta Líquida (Outflows Masivos)' },
      neutral: { min: 2300000, max: 2700000, label: 'Equilibrio de Inventario' },
      overheated: { min: 2700000, max: 4000000, label: 'Exceso de Liquidez en Venta (Inflows)' },
    },
    currentStatus: 'ACCUMULATION',
    formula: 'Σ(Monedas custodiadas en billeteras verificadas de Exchanges centralizados)',
    interpretation: 'Una tendencia descendente prolongada de reservas refleja que los inversores retiran sus BTC hacia billeteras frías para custodia soberana, reduciendo la oferta flotante.',
    importance: 'CRITICAL',
  },
  {
    id: 'metric-realized-price',
    name: 'Precio Realizado (Costo Base On-Chain)',
    symbol: 'REALIZED',
    sourceId: 'nodecharts',
    sourceName: 'NodeCharts / BitBo',
    sourceUrl: 'https://nodecharts.com',
    currentValue: 34620,
    formattedValue: '$34,620 USD',
    unit: 'USD',
    historicalRange: { min: 100, max: 100000, mean: 28000 },
    zones: {
      accumulation: { min: 0, max: 34620, label: 'Precio Spot bajo Precio Realizado (Suelo Absoluto)' },
      neutral: { min: 34620, max: 90000, label: 'Spot por encima de Costo Base' },
      overheated: { min: 90000, max: 250000, label: 'Prima de Valoración Extrema (>3x)' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: 'Capitalización Realizada (USD) / Suministro Circulante Total',
    interpretation: 'Representa el coste medio agregado al que se movió cada bitcoin existente por última vez en la blockchain. Actúa como piso fundamental psicológico en mercados bajistas.',
    importance: 'CRITICAL',
  },
  {
    id: 'metric-rhodl',
    name: 'RHODL Ratio (Realized HODL)',
    symbol: 'RHODL',
    sourceId: 'look-into-bitcoin',
    sourceName: 'Look Into Bitcoin',
    sourceUrl: 'https://www.lookintobitcoin.com/charts/rhodl-ratio/',
    currentValue: 3120,
    formattedValue: '3,120',
    historicalRange: { min: 180, max: 48000, mean: 2900 },
    zones: {
      accumulation: { min: 0, max: 800, label: 'Banda Verde de Acumulación' },
      neutral: { min: 800, max: 8000, label: 'Zona Media de Consolidación' },
      overheated: { min: 8000, max: 60000, label: 'Banda Roja de Máximo de Ciclo' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: 'RHODL Band 1 semana / RHODL Band 1 a 2 años * factor de corrección por antigüedad',
    interpretation: 'Compara el capital de compradores recientes (1 semana) contra inversores veteranos (1-2 años). Identifica si el mercado está dominado por novatos en FOMO o manos fuertes.',
    importance: 'HIGH',
  },
  {
    id: 'metric-lightning-capacity',
    name: 'Capacidad de Red Lightning Network',
    symbol: 'LN-CAP',
    sourceId: 'bitcoin-visuals',
    sourceName: 'Bitcoin Visuals / 1ML',
    sourceUrl: 'https://bitcoinvisuals.com/lightning',
    currentValue: 5840,
    formattedValue: '5,840 BTC',
    unit: 'BTC',
    historicalRange: { min: 50, max: 10000, mean: 4200 },
    zones: {
      accumulation: { min: 0, max: 3000, label: 'Desarrollo Inicial L2' },
      neutral: { min: 3000, max: 8000, label: 'Adopción Comercial Estable' },
      overheated: { min: 8000, max: 50000, label: 'Canalización Masiva Institucional' },
    },
    currentStatus: 'FAIR_VALUE',
    formula: 'Σ(Capacidad pública bloqueada en canales 2-de-2 multisig de Lightning Network)',
    interpretation: 'Indica la liquidez total disponible para transacciones instantáneas y micropagos sin ocupar espacio en los bloques de la capa 1 de Bitcoin.',
    importance: 'MEDIUM',
  },
  {
    id: 'metric-stenox-anomaly',
    name: 'Stenox Smart Money Momentum',
    symbol: 'STENOX-SMM',
    sourceId: 'stenox-ai',
    sourceName: 'Stenox.ai Quant Engine',
    sourceUrl: 'https://stenox.ai',
    currentValue: 78.4,
    formattedValue: '78.4 / 100',
    unit: 'Score',
    historicalRange: { min: 10, max: 98, mean: 52 },
    zones: {
      accumulation: { min: 0, max: 35, label: 'Apatía / Sin Presión Institucional' },
      neutral: { min: 35, max: 70, label: 'Volumen y Flujos Neutros' },
      overheated: { min: 70, max: 100, label: 'Fuerte Flujo Institucional Detectado' },
    },
    currentStatus: 'EUPHORIA',
    formula: 'Algoritmo de clustering sobre entradas a cold wallets institucionales y swaps OTC',
    interpretation: 'Puntuación generada por inteligencia artificial que identifica compras sigilosas de fondos y ballenas fuera de los libros visibles de exchanges tradicionales.',
    importance: 'HIGH',
  },
];

export const CORRELATION_DATASET: CorrelationPairData[] = [
  {
    pair: 'BTC / XAU (Oro Físico)',
    assetName: 'Oro al Contado (Gold Spot)',
    category: 'Commodities',
    corr30d: 0.38,
    corr90d: 0.46,
    corr1y: 0.52,
    historicalTrend: 'POSITIVE',
    description: 'Correlación positiva moderada. Ambos activos reaccionan de manera favorable ante la expansión de la masa monetaria global (M2) y la degradación de monedas fiduciarias.',
    source: 'Mataf / NodeCharts Macro',
    economicMeaning: 'Validación del rol de Bitcoin como "Oro Digital" con oferta inelástica y propiedades monetarias superiores de transferibilidad y verificabilidad.',
  },
  {
    pair: 'BTC / S&P 500 (SPX)',
    assetName: 'S&P 500 Index',
    category: 'Equities',
    corr30d: 0.42,
    corr90d: 0.35,
    corr1y: 0.31,
    historicalTrend: 'DECOUPLED',
    description: 'Correlación fluctuante que tiende a desacoplarse durante fases de madurez de ciclo. Muestra correlación alta únicamente en pánicos de liquidez masiva (ej. marzo 2020).',
    source: 'Mataf / Bloomberg Analytics',
    economicMeaning: 'Bitcoin se comporta como activo de riesgo tecnológico en ventanas cortas, pero preserva primas asimétricas independientes en horizontes plurianuales.',
  },
  {
    pair: 'BTC / DXY (US Dollar Index)',
    assetName: 'Índice Dólar de EE.UU.',
    category: 'Fiat & Macro',
    corr30d: -0.62,
    corr90d: -0.58,
    corr1y: -0.65,
    historicalTrend: 'INVERSE',
    description: 'Fuerte correlación inversa consistente. Las etapas de fortalecimiento agresivo del dólar generan vientos en contra para Bitcoin, mientras que la debilidad del DXY impulsa rallies parabólicos.',
    source: 'Mataf Macro Radar',
    economicMeaning: 'Bitcoin actúa como la antítesis del monopolio emisor del dólar fiat. Cuando la liquidez del dólar se contrae, los activos de oferta fija experimentan presión.',
  },
  {
    pair: 'BTC / NASDAQ 100 (NDX)',
    assetName: 'Nasdaq 100 Tech Index',
    category: 'Equities',
    corr30d: 0.48,
    corr90d: 0.41,
    corr1y: 0.39,
    historicalTrend: 'POSITIVE',
    description: 'Correlación moderada ligada al apetito global por innovación computacional y tasas de descuento de los bancos centrales.',
    source: 'Mataf / CryptoCompare',
    economicMeaning: 'Sensibilidad compartida a las decisiones de tipos de interés de la Reserva Federal (Fed Funds Rate).',
  },
  {
    pair: 'BTC / Global M2 Money Supply',
    assetName: 'Masa Monetaria Global M2',
    category: 'Fiat & Macro',
    corr30d: 0.74,
    corr90d: 0.81,
    corr1y: 0.86,
    historicalTrend: 'POSITIVE',
    description: 'La correlación macro más robusta de todas (+0.86). El precio de Bitcoin sigue con una precisión matemática casi perfecta la tasa de variación de la liquidez global de los bancos centrales.',
    source: 'Look Into Bitcoin / Raoul Pal Macro',
    economicMeaning: 'Bitcoin no es solo un activo especulativo: es el barómetro más sensible del planeta sobre la degradación inflacionaria del dinero fiduciario.',
  },
  {
    pair: 'BTC / Ethereum (ETH)',
    assetName: 'Ethereum (Ether)',
    category: 'Crypto Native',
    corr30d: 0.84,
    corr90d: 0.88,
    corr1y: 0.82,
    historicalTrend: 'POSITIVE',
    description: 'Alta correlación intradía dentro del ecosistema cripto, aunque la dominancia de Bitcoin tiende a expandirse en periodos bajistas y contraerse en alt-seasons.',
    source: 'CoinGecko / CryptoCompare',
    economicMeaning: 'Bitcoin lidera la liquidez estructural; Ethereum y el ecosistema DeFi operan con una beta amplificada dependiente del ciclo de BTC.',
  },
  {
    pair: 'BTC / US 10-Year Treasury Yield',
    assetName: 'Rendimiento del Bono del Tesoro a 10 Años',
    category: 'Fiat & Macro',
    corr30d: -0.32,
    corr90d: -0.28,
    corr1y: -0.36,
    historicalTrend: 'INVERSE',
    description: 'Correlación negativa moderada. Tipos de interés reales más altos elevan el coste de oportunidad del capital no remunerado.',
    source: 'Mataf Economics',
    economicMeaning: 'Aumentos en el rendimiento sin riesgo ejercen presión competitiva transitoria sobre los activos de reserva de valor.',
  },
];

export class OnChainAnalyticsHub {
  public static getAllSources(): OnChainSourceEntry[] {
    return PRIMARY_ONCHAIN_SOURCES;
  }

  public static getSourcesByCategory(category: string): OnChainSourceEntry[] {
    if (category === 'ALL') return PRIMARY_ONCHAIN_SOURCES;
    return PRIMARY_ONCHAIN_SOURCES.filter((s) => s.category === category);
  }

  public static getDetailedMetrics(): OnChainDetailedMetric[] {
    return PRIMARY_ONCHAIN_METRICS;
  }

  public static getCorrelationDataset(): CorrelationPairData[] {
    return CORRELATION_DATASET;
  }
}
