import { RegulatoryItem } from '../../types';

export const REGULATORY_DATABASE: RegulatoryItem[] = [
  {
    id: 'reg-arg-cnv-994',
    jurisdiction: 'Argentina',
    agency: 'CNV (Comisión Nacional de Valores)',
    date: '2024-03-25',
    normReference: 'Resolución General CNV N° 994/2024',
    status: 'Vigente',
    summary: 'Crea e implementa el Registro de Proveedores de Servicios de Activos Virtuales (PSAV) en cumplimiento con la Ley N° 27.739 de prevención de lavado de activos (PLA/FT), estableciendo requisitos de inscripción obligatoria para exchanges y custodios domiciliados u operando en Argentina.',
    primarySourceUrl: 'https://www.argentina.gob.ar/normativa/recurso/399427/texact/htm',
    affectedParties: 'Exchanges locales, plataformas P2P con establecimiento permanente, pasarelas de pago cripto.',
    disclaimer: 'Información normativa de carácter educativo y referencial. No constituye dictamen ni asesoramiento legal vinculante.',
  },
  {
    id: 'reg-arg-arca-4614',
    jurisdiction: 'Argentina',
    agency: 'ARCA (ex AFIP - Agencia de Recaudación y Control Aduanero)',
    date: '2024-07-15',
    normReference: 'Resolución General AFIP N° 4614/2019 (y modif. RG 5594)',
    status: 'Vigente',
    summary: 'Régimen informativo mensual obligatorio para administradores de plataformas virtuales y exchanges sobre cuentas de usuarios, movimientos, ingresos/egresos y saldos en moneda de curso legal y activos virtuales.',
    primarySourceUrl: 'https://www.afip.gob.ar',
    affectedParties: 'Plataformas de custodia, billeteras virtuales registradas, intermediarios financieros.',
    disclaimer: 'Documento de análisis tributario normativo. Se recomienda consultar al contador público matriculado para casos concretos.',
  },
  {
    id: 'reg-arg-uif-49',
    jurisdiction: 'Argentina',
    agency: 'UIF (Unidad de Información Financiera)',
    date: '2024-04-10',
    normReference: 'Resolución UIF N° 49/2024',
    status: 'Vigente',
    summary: 'Establece los lineamientos de gestión de riesgos de lavado de activos y financiamiento del terrorismo que deben adoptar los Proveedores de Servicios de Activos Virtuales (PSAV), incluyendo la regla de viaje (Travel Rule) recomendada por el GAFI/FATF.',
    primarySourceUrl: 'https://www.argentina.gob.ar/uif',
    affectedParties: 'Oficiales de Cumplimiento, PSAV, entidades financieras conectadas a rampas fiat.',
    disclaimer: 'Normativa contra el blanqueo de capitales. Marco regulatorio sujeto a actualización periódica por el GAFI.',
  },
  {
    id: 'reg-arg-bcra-7506',
    jurisdiction: 'Argentina',
    agency: 'BCRA (Banco Central de la República Argentina)',
    date: '2022-05-05',
    normReference: 'Comunicación "A" 7506 y "A" 7759',
    status: 'Vigente',
    summary: 'Dispone que las entidades financieras y los proveedores de servicios de pago que ofrecen cuentas de pago (PSPCP) no pueden facilitar a sus clientes la realización de operaciones con activos digitales que no se encuentren regulados por la autoridad nacional competente.',
    primarySourceUrl: 'https://www.bcra.gob.ar',
    affectedParties: 'Bancos comerciales, billeteras fintech híbridas no registradas como PSAV.',
    disclaimer: 'Restricción prudencial de vinculación entre el sistema bancario tradicional y criptoactivos directos.',
  },
  {
    id: 'reg-eu-mica',
    jurisdiction: 'Unión Europea',
    agency: 'Parlamento Europeo / ESMA / EBA',
    date: '2024-12-30',
    normReference: 'Reglamento (UE) 2023/1114 (MiCA - Markets in Crypto-Assets)',
    status: 'Vigente',
    summary: 'Marco regulatorio integral armonizado para la emisión, custodia y prestación de servicios de criptoactivos en los 27 estados miembros de la UE. Divide los activos en e-money tokens (EMT), asset-referenced tokens (ART) y otros tokens (incluyendo utility tokens), imponiendo estrictos requisitos de solvencia y reserva.',
    primarySourceUrl: 'https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=CELEX:32023R1114',
    affectedParties: 'CASPs (Crypto-Asset Service Providers), emisores de stablecoins globales.',
    disclaimer: 'Bitcoin per se queda categorizado como criptoactivo no respaldado por emisor centralizado.',
  },
  {
    id: 'reg-us-sab121',
    jurisdiction: 'Estados Unidos',
    agency: 'SEC / CFTC / FinCEN',
    date: '2024-05-20',
    normReference: 'SEC Staff Accounting Bulletin No. 121 (SAB 121) / FIT21 Review',
    status: 'En Consulta',
    summary: 'Tratamiento contable de obligaciones de custodia de criptoactivos para entidades reportantes ante la SEC. Obliga a reconocer pasivo y activo compensatorio a valor razonable, encareciendo el capital regulatorio para bancos custodios de Bitcoin.',
    primarySourceUrl: 'https://www.sec.gov',
    affectedParties: 'Bancos custodios estadounidenses (BNY Mellon, State Street), custodios institucionales de ETFs.',
    disclaimer: 'Materia sujeta a debate legislativo y posibles resoluciones conjuntas del Congreso de EE.UU.',
  },
  {
    id: 'reg-sv-btc-law',
    jurisdiction: 'El Salvador',
    agency: 'Asamblea Legislativa / CNAD',
    date: '2021-09-07',
    normReference: 'Decreto Legislativo N° 57 - Ley Bitcoin & Ley de Emisión de Activos Digitales',
    status: 'Vigente',
    summary: 'Otorga curso legal a Bitcoin en todo el territorio salvadoreño con poder liberatorio ilimitado, complementado con la Ley de Emisión de Activos Digitales (Decreto N° 642) y supervisión por la Comisión Nacional de Activos Digitales (CNAD).',
    primarySourceUrl: 'https://www.cnad.gob.sv',
    affectedParties: 'Comercios, residentes, emisores de bonos volcán e instrumentos estructurados.',
    disclaimer: 'Única jurisdicción soberana donde Bitcoin ostenta estatus pleno de moneda de curso legal.',
  },
  {
    id: 'reg-br-14478',
    jurisdiction: 'Brasil',
    agency: 'Banco Central do Brasil (BCB) / CVM',
    date: '2023-06-20',
    normReference: 'Lei Nº 14.478/2022 (Marco Legal dos Criptoativos)',
    status: 'Vigente',
    summary: 'Define las directrices para la prestación de servicios de activos virtuales y asigna al Banco Central do Brasil la regulación y supervisión de las prestadoras de servicios (VASPs), protegiendo la segregación patrimonial de fondos de clientes.',
    primarySourceUrl: 'https://www.bcb.gov.br',
    affectedParties: 'Exchanges e instituciones de pago en territorio brasileño.',
    disclaimer: 'Pionero en Latinoamérica en exigir segregación contable obligatoria de activos de usuarios.',
  },
];
